sudo: required
services:
        - docker


before_install:
        - docker build -t kengang/docker-react -f dockerfile.dev .


script:
        - docker run kengang/docker-react npm run test -- --coverage 
