sudo: required
services:
        - docker


before_install:
        - docker build -t kengang/docker-react -f dockerfile.dev .


script:
        - docker run kengang/docker-react npm run test -- --coverage 

before_deploy:
          - rvm 1.9.3 do gem install aws-sdk -v 2.1.36

deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "dockertest"
        env: "Dockertest-env"
        bucket_name: "elasticbeanstalk-us-east-1-504949500814"
        bucket_path: "dockertest"
        on: 
           branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
           secure: "$AWS_SECRET_KEY"
